// <auto-generated />
using System;
using CandyShopV2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CandyShopV2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200116084314_AddedOrder")]
    partial class AddedOrder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CandyShopV2.Models.Candy", b =>
                {
                    b.Property<int>("CandyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CatagoryId")
                        .HasColumnType("int");

                    b.Property<string>("Descrition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageThumbNail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnStock")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CandyId");

                    b.HasIndex("CatagoryId");

                    b.ToTable("Candies");

                    b.HasData(
                        new
                        {
                            CandyId = 1,
                            CatagoryId = 3,
                            Descrition = "Very sweet",
                            ImageThumbNail = "C:\\Users\\Mathias\\source\\repos\\CandyShopV2\\CandyShopV2\\wwwroot\\images\\thumbnails\\FruitCandy-small.jpg",
                            ImageUrl = "C:\\Users\\Mathias\\source\\repos\\CandyShopV2\\CandyShopV2\\wwwroot\\images\\FruitCandy.jpg",
                            IsOnSale = true,
                            IsOnStock = true,
                            Name = "Sweet candy",
                            Price = 20m
                        },
                        new
                        {
                            CandyId = 2,
                            CatagoryId = 2,
                            Descrition = "Very sour",
                            ImageThumbNail = "C:\\Users\\Mathias\\source\\repos\\CandyShopV2\\CandyShopV2\\wwwroot\\images\\thumbnails\\halloweenCandy-small.jpg",
                            ImageUrl = "C:\\Users\\Mathias\\source\\repos\\CandyShopV2\\CandyShopV2\\wwwroot\\images\\halloweenCandy.jpg",
                            IsOnSale = true,
                            IsOnStock = true,
                            Name = "Sour",
                            Price = 50m
                        },
                        new
                        {
                            CandyId = 3,
                            CatagoryId = 1,
                            Descrition = "Very beary",
                            ImageThumbNail = "C:\\Users\\Mathias\\source\\repos\\CandyShopV2\\CandyShopV2\\wwwroot\\images\\gummyCandy2.jpg",
                            ImageUrl = "C:\\Users\\Mathias\\source\\repos\\CandyShopV2\\CandyShopV2\\wwwroot\\images\\thumbnails\\gummyCandy2-small.jpg",
                            IsOnSale = true,
                            IsOnStock = true,
                            Name = "Gummy bears",
                            Price = 5m
                        });
                });

            modelBuilder.Entity("CandyShopV2.Models.Catagory", b =>
                {
                    b.Property<int>("CatagoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CatagoryId");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            CatagoryId = 1,
                            CategoryDescription = "The worst candy",
                            CategoryName = "Chocolate candy"
                        },
                        new
                        {
                            CatagoryId = 3,
                            CategoryDescription = "This is the one for candys with P.H levels below 6",
                            CategoryName = "Sweet"
                        },
                        new
                        {
                            CatagoryId = 2,
                            CategoryDescription = "This is the one for candys with P.H levels above 6",
                            CategoryName = "Sore"
                        });
                });

            modelBuilder.Entity("CandyShopV2.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("OrderPlaced")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("Zipcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CandyShopV2.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<int>("CandyId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("CandyId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("CandyShopV2.Models.ShoppingCardItem", b =>
                {
                    b.Property<int>("ShoppingCardItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("CandyId")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCardId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShoppingCardItemId");

                    b.HasIndex("CandyId");

                    b.ToTable("ShoppingCardItems");
                });

            modelBuilder.Entity("CandyShopV2.Models.Candy", b =>
                {
                    b.HasOne("CandyShopV2.Models.Catagory", "Catagory")
                        .WithMany("Candies")
                        .HasForeignKey("CatagoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CandyShopV2.Models.OrderDetail", b =>
                {
                    b.HasOne("CandyShopV2.Models.Candy", "Candy")
                        .WithMany()
                        .HasForeignKey("CandyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CandyShopV2.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CandyShopV2.Models.ShoppingCardItem", b =>
                {
                    b.HasOne("CandyShopV2.Models.Candy", "Candy")
                        .WithMany()
                        .HasForeignKey("CandyId");
                });
#pragma warning restore 612, 618
        }
    }
}
